/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Handle for the background clipboard watcher `start_clipboard_watcher` starts. Dropping this
 * without calling `stop()` leaks the watcher window and its message-loop thread for the rest of
 * the process's life — callers must `stop()` it explicitly (e.g. on app quit), matching
 * `ClipboardPoller.stop()` on the TS side.
 */
export declare class ClipboardWatcher {
  /**
   * Unregisters the clipboard listener, closes the hidden watcher window, and joins its
   * message-loop thread. Idempotent — a second call is a no-op.
   */
  stop(): void
}

/**
 * Handle for the background hotkey watcher `start_hotkey_watcher` starts.
 * Dropping this without calling `stop()` leaks the watcher window, the
 * keyboard hook, and its message-loop thread for the rest of the process's
 * life — callers must `stop()` it explicitly (e.g. on app quit).
 */
export declare class HotkeyWatcher {
  /**
   * Parses and stores `accelerator` under `id`, replacing whatever was
   * previously registered under that id. Returns `false` only if
   * `accelerator` doesn't parse (an unmapped key token, or no modifier at
   * all) — unlike `RegisterHotKey`, there's no "already in use by another
   * app" failure mode here, since this never asks Windows for exclusive
   * ownership of the combo; it just watches every keystroke itself.
   */
  register(id: string, accelerator: string): boolean
  /** Idempotent — removing an id that isn't registered is a no-op. */
  unregister(id: string): void
  /**
   * Starts reporting every `Win`-involving keystroke to `callback` as a
   * captured accelerator string (`"Super"` for a lone tap, `"Super+Space"`
   * for a combo, …) instead of matching it against registered entries —
   * for a shortcut-recorder UI, which otherwise has no way to see a `Win`
   * keystroke at all (see `HookState::capturing`). A key that doesn't
   * involve `Win` is untouched and keeps reaching the focused window's own
   * keydown handler exactly as before. Replaces any previous capture
   * callback if already capturing.
   */
  startCapture(callback: ((err: Error | null, arg: string) => any)): void
  /** Stops capture mode and resumes normal entry-matching. Idempotent. */
  stopCapture(): void
  /**
   * Unhooks, closes the hidden watcher window, and joins its message-loop
   * thread. Idempotent.
   */
  stop(): void
}

/**
 * Restores a maximized/minimized window, then moves/resizes it so its *visible*
 * frame (see `get_window_rect`) exactly matches `rect` — expanding by the
 * invisible resize border so adjacent tiled windows still sit flush, the way
 * Windows' own Snap does — and brings it to the foreground. `rect` is expected to
 * already be a valid target the caller computed (from `window/layout.ts`); this
 * function does no region math of its own. Returns whether the window was moved.
 */
export declare function applyWindowRect(hwnd: number, rect: WinRect): boolean

/**
 * Extracts the icon embedded in a PE file (.exe/.dll) at the given resource index and
 * returns it as PNG bytes, or `null` if the file has no icon at that index.
 */
export declare function extractIconPng(path: string, index: number): Buffer | null

/**
 * Renders the tile icon for a packaged (MSIX/UWP) app via the same
 * `IShellItemImageFactory` mechanism Explorer uses, addressed by its
 * AppUserModelID under the virtual `shell:AppsFolder`.
 */
export declare function extractPackagedIconPng(appId: string, size: number): Buffer | null

/**
 * The current foreground window handle, as an i64 (USER handles fit in 32 bits even
 * on 64-bit Windows). The launcher captures this just before it shows itself, so the
 * window-snap commands act on whatever the user was working in, not on the launcher.
 */
export declare function foregroundWindow(): number

/**
 * The window's current visible frame — DWM's extended frame bounds, i.e. the
 * painted pixels, not the underlying window rect (which can carry several px of
 * invisible resize border on the left/right/bottom). This is the same
 * screen-coordinate space Electron's `screen` module reports display work areas
 * in, so callers (TS `window/layout.ts` via `screen.getDisplayNearestPoint`) can
 * use it directly with no translation. Returns `null` if `hwnd` is invalid or DWM
 * can't report its frame (e.g. a custom-framed app).
 */
export declare function getWindowRect(hwnd: number): WinRect | null

/**
 * Terminates `pid` via `TerminateProcess` — `force` has no effect on
 * Windows (see the module comment above); kept for a call-shape identical
 * to macOS/Linux. Returns `false` if the process no longer exists or
 * access is denied; the caller can't tell those apart from the bool alone
 * and doesn't need to — both are surfaced as the same inline error.
 */
export declare function killProcess(pid: number, force: boolean): boolean

/**
 * Every TCP port something is listening on, with the owning pid. Empty if the
 * OS refuses to enumerate (e.g. missing permission).
 */
export declare function listListeningPorts(): Array<NativePort>

/**
 * A snapshot of every currently running process's pid, name, CPU% and
 * working-set memory. Cheap to call on a poll interval (a couple of times a
 * second).
 */
export declare function listProcesses(): Array<NativeProcess>

/**
 * Enumerates packaged (MSIX/UWP) Start Menu apps by walking the virtual
 * `shell:AppsFolder`, replacing the `Get-StartApps` PowerShell cmdlet. Only items
 * whose AppUserModelID contains `!` (PackageFamilyName!AppId) are packaged apps;
 * classic desktop apps also show up in this folder but are already covered by the
 * `.lnk` shortcuts collected separately, so they're filtered out here.
 */
export declare function listStartApps(): Array<StartApp>

/**
 * One listening TCP socket and the process that owns it. Cheap enough (a few
 * ms) to fetch alongside `list_processes()` on every poll tick.
 */
export interface NativePort {
  pid: number
  port: number
}

/**
 * One process's identity and live resource usage, as reported by the last
 * `list_processes()` refresh.
 */
export interface NativeProcess {
  pid: number
  name: string
  /**
   * Percentage of a single CPU core (0–100 per core, so a busy multi-core
   * process can exceed 100), matching Task Manager's own convention.
   */
  cpuUsage: number
  memoryBytes: number
  /**
   * Full path to the executable, when readable — lets the TS side resolve
   * an icon for it via Electron's `app.getFileIcon`. `None` for a process
   * whose executable path isn't readable (permission-restricted, or exited
   * between the refresh and this read).
   */
  path?: string
}

/**
 * Reads a `.lnk` shortcut's target path and icon location, replacing the
 * `WScript.Shell` COM object previously driven from PowerShell.
 */
export declare function resolveShortcut(path: string): ShortcutInfo | null

export interface ShortcutInfo {
  targetPath: string
  iconPath: string
  iconIndex: number
}

export interface StartApp {
  name: string
  appId: string
}

/**
 * Starts watching the system clipboard for changes via a true OS push notification instead of
 * polling: a background thread creates a hidden, message-only window, registers it for
 * `WM_CLIPBOARDUPDATE` via `AddClipboardFormatListener` (the Win32 mechanism the Windows Clipboard
 * History pane itself is built on), and invokes `callback` with no arguments once for every
 * clipboard write. This is what lets the TS `ClipboardPoller` (see
 * `main/pasteboard-change-win.ts`) skip its `setInterval` fallback entirely on Windows, unlike the
 * cheap-but-still-polled `pasteboardChangeCount()` this addon's macOS counterpart offers.
 *
 * Blocks briefly (microseconds — one window creation) waiting for the background thread to
 * finish setting up before returning, so a failure (window/class creation, or registering the
 * listener) can be reported by returning a watcher whose `hwnd` is already 0 rather than a
 * handle that silently never calls back.
 */
export declare function startClipboardWatcher(callback: ((err: Error | null, ) => any)): ClipboardWatcher

/**
 * Starts the global-hotkey watcher: a background thread creates a hidden,
 * message-only window, installs a system-wide `WH_KEYBOARD_LL` hook on that
 * thread (required — Windows delivers low-level hook callbacks only to the
 * thread that installed them, via its message loop), and invokes `callback`
 * with the registered id whenever a bound accelerator fires. Entries are
 * registered/unregistered afterward via the returned `HotkeyWatcher`.
 *
 * Blocks briefly (microseconds — one window + hook creation) waiting for the
 * background thread to finish setting up, so a failure can be reported by
 * returning a watcher whose `hwnd` is already 0 rather than one that
 * silently never calls back — same contract as `start_clipboard_watcher`.
 */
export declare function startHotkeyWatcher(callback: ((err: Error | null, arg: string) => any)): HotkeyWatcher

/**
 * Windows has no equivalent of macOS's Spaces-based fullscreen, so "Toggle
 * Fullscreen" maps to the closest native analogue: maximize the window (or
 * restore it, if already maximized). Returns whether the state changed.
 */
export declare function toggleMaximize(hwnd: number): boolean

export interface WinRect {
  x: number
  y: number
  width: number
  height: number
}
