/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Handle for the background hotkey watcher `start_hotkey_watcher` starts.
 * Dropping this without calling `stop()` leaks the event tap and its
 * run-loop thread for the rest of the process's life — callers must
 * `stop()` it explicitly (e.g. on app quit), mirroring `native/win`'s
 * `HotkeyWatcher`.
 */
export declare class HotkeyWatcher {
  /**
   * Parses and stores `accelerator` under `id`, replacing whatever was
   * previously registered under that id. Returns `false` if `accelerator`
   * doesn't parse, or if a *different* id already holds the exact same
   * modifiers+key — unlike `globalShortcut`, this never asks macOS for
   * exclusive ownership of the combo (it just watches, and on a match
   * suppresses, every keystroke itself), so nothing upstream would ever
   * reject a genuine duplicate on its own: without this check, `entries`
   * would happily hold two ids for the same combo, and whichever happened
   * to land first in the list would silently keep winning every match in
   * `handle_key_event`/`handle_flags_changed` forever, while the *other*
   * id's `register()` call reported success anyway.
   */
  register(id: string, accelerator: string): boolean
  /** Idempotent — removing an id that isn't registered is a no-op. */
  unregister(id: string): void
  /**
   * Starts reporting every reportable keystroke (any `mods+key` press, or a
   * modifier-only chord's release) to `callback` as a captured accelerator
   * string, instead of matching it against registered entries — see
   * `HookState::capturing`'s doc comment for why a shortcut recorder needs
   * this rather than its own DOM listener: an already-bound combo would
   * otherwise never reach this process at all. A keystroke with no modifier
   * held is untouched and keeps reaching the focused window's own keydown
   * handler exactly as before (Escape-to-cancel, Enter-to-confirm, …).
   * Replaces any previous capture callback if already capturing.
   */
  startCapture(callback: ((err: Error | null, arg: string) => any)): void
  /** Stops capture mode and resumes normal entry-matching. Idempotent. */
  stopCapture(): void
  /**
   * Disables and invalidates the tap, stops its run loop, and joins the
   * background thread. Idempotent.
   */
  stop(): void
}

/**
 * What a form shows. `kind` is `"text"` (a text field) or `"keys"` (records the
 * next key combo, as an Electron accelerator like `Command+Shift+K`).
 */
export interface ActionsFormSpec {
  kind: string
  title: string
  /** A glyph (emoji) shown before the title. */
  iconText?: string
  /** A `data:image/...;base64,` icon shown before the title. */
  iconDataUrl?: string
  /** Text mode: the field's starting content. */
  initialValue?: string
  /** Text mode: the field's placeholder. */
  placeholder?: string
  /** Text mode: drop whitespace as it's typed. */
  stripWhitespace?: boolean
  /** Left button, default "Cancel". */
  cancelLabel?: string
  /** Right (primary) button, default "Save". */
  submitLabel?: string
  /** The primary button's title while saving, default "Saving…". */
  loadingLabel?: string
}

/** One row of the panel. Mirrors the renderer's `ActionsPanelItem`. */
export interface ActionsPanelItem {
  id: string
  title: string
  /** Rows sharing a section are grouped under a small header. */
  section?: string
  /** Keycaps, e.g. `["⇧", "⌘", "F"]`. */
  shortcut?: Array<string>
  /** SF Symbol name, e.g. `"star"`. */
  iconSfSymbol?: string
  /**
   * SF Symbol shown at the trailing edge, after any keycaps — e.g.
   * `"chevron.right"` on a row that opens a submenu.
   */
  accessorySfSymbol?: string
  /**
   * Plain text at the trailing edge where the keycaps would sit, for a value
   * that isn't a shortcut (e.g. the current alias). Ignored if `shortcut` is set.
   */
  hint?: string
  danger?: boolean
}

/**
 * Moves and resizes the focused window to `rect`. Sets size, then position, then
 * size again — some apps clamp or reflow their frame when it lands near a screen
 * edge, and re-asserting the size after the move is what makes the final result
 * stick (same workaround the AppleScript version used). Returns whether both
 * attributes were written successfully.
 */
export declare function applyWindowRect(pid: number, rect: MacRect): boolean

/** Closes the form without reporting anything back — the caller is done with it. */
export declare function closeActionsForm(): void

/** Dismisses the panel if one is open (reports `{ kind: "close" }`). */
export declare function closeActionsPanel(): void

/**
 * On-disk size of each directory (or file) in `paths`, in the same order.
 * Async — the walk of a multi-gigabyte `DerivedData` runs on the libuv
 * thread pool, so the Electron main process never blocks on it.
 */
export declare function dirSize(paths: Array<string>): Promise<Array<DirSize>>

/** One directory's on-disk footprint, as reported by `dir_size()`. */
export interface DirSize {
  path: string
  /**
   * Bytes actually allocated on disk (`st_blocks * 512`, what `du` and
   * Finder's "size on disk" report) — not the sum of logical file lengths,
   * which overstates sparse files and understates block-rounded small ones.
   */
  bytes: number
  fileCount: number
  /**
   * Newest modification time among the directory itself and its direct
   * children, in epoch milliseconds — cheap "last used" signal for the UI.
   */
  modifiedMs: number
}

/**
 * Tells the open form its save failed: it shows `message` and lets the user
 * try again. Does nothing if no form is open.
 */
export declare function failActionsForm(message: string): void

/**
 * What a form reports: `kind` is `"submit"` (with the `value`) or `"cancel"`
 * (with `value` `"back"` if the user chose to leave, `"dismissed"` if it was lost).
 */
export interface FormEvent {
  kind: string
  value?: string
}

/**
 * The pid of the frontmost real application window, or `0` if none is found
 * (e.g. every window is a desktop element, or the list is empty). `exclude` is
 * our own pid — the launcher itself can briefly be the frontmost window right as
 * it's shown/hidden, and capturing it would mean later commands snap our own
 * window instead of whatever the user was actually working in.
 *
 * `CGWindowListCopyWindowInfo` needs no special permission and reports windows
 * front-to-back by on-screen stacking order, so the first entry whose layer is 0
 * (an ordinary app window — the Dock, menu bar, etc. use nonzero layers) and
 * whose owner isn't `exclude` is exactly "what the user was looking at."
 */
export declare function frontmostPid(exclude: number): number

/**
 * The focused window's current position and size, or `null` if unavailable
 * (no focused window, invalid pid, or Accessibility access not granted).
 */
export declare function getWindowRect(pid: number): MacRect | null

/**
 * Whether the focused window is currently in native macOS fullscreen (its own
 * Space). `false` for anything that can't be determined (no focused window,
 * permission not granted, or the window doesn't support this attribute at all —
 * `AXFullScreen` isn't part of the standard Accessibility attribute set, so a
 * missing-attribute error here just means "this app doesn't offer fullscreen,"
 * not a real failure).
 */
export declare function isFullscreen(pid: number): boolean

/**
 * Terminates `pid` — `SIGTERM` (a graceful "Quit") when `force` is `false`,
 * `SIGKILL` ("Force Quit") when `true`. Returns `false` if the process no
 * longer exists or the OS denies permission (not owned by this user); the
 * caller can't tell those apart from the bool alone and doesn't need to —
 * both are surfaced as the same inline error.
 */
export declare function killProcess(pid: number, force: boolean): boolean

/**
 * Every TCP port something is listening on, with the owning pid. Empty if the
 * OS refuses to enumerate (e.g. missing permission).
 */
export declare function listListeningPorts(): Array<NativePort>

/**
 * A snapshot of every currently running process's pid, name, CPU% and
 * resident memory. Cheap to call on a poll interval (a couple of times a
 * second) — the underlying refresh only re-reads `/proc`-equivalent process
 * tables, no per-call allocation of a new `System`.
 */
export declare function listProcesses(): Array<NativeProcess>

export interface MacRect {
  x: number
  y: number
  width: number
  height: number
}

/**
 * One listening TCP socket and the process that owns it. Cheap enough (a few
 * ms) to fetch alongside `list_processes()` on every poll tick.
 */
export interface NativePort {
  pid: number
  port: number
}

/**
 * One process's identity and live resource usage, as reported by the last
 * `list_processes()` refresh.
 */
export interface NativeProcess {
  pid: number
  name: string
  /**
   * Percentage of a single CPU core (0–100 per core, so a busy multi-core
   * process can exceed 100), matching Activity Monitor's own convention.
   */
  cpuUsage: number
  memoryBytes: number
  /**
   * Full path to the executable, when readable — lets the TS side resolve
   * an app icon (walking up to the enclosing `.app` bundle on macOS, since
   * the raw Mach-O binary carries no icon of its own). `None` for a process
   * whose executable path isn't readable (permission-restricted, or exited
   * between the refresh and this read).
   */
  path?: string
}

/** What the panel reports back: `kind` is `"select"` (with `id`) or `"close"`. */
export interface PanelEvent {
  kind: string
  id?: string
}

/**
 * `NSPasteboard.generalPasteboard.changeCount` — a counter AppKit increments
 * every time the general pasteboard's *content* changes (a copy, a cut, or
 * any programmatic write), and never otherwise. macOS has no pasteboard
 * "changed" notification/event at all — every clipboard-history app,
 * Raycast included, is built around polling *something*; the point of this
 * export is to make that something cheap. Reading it costs nothing (no IPC,
 * no permission prompt, no clipboard format negotiation) — a poller can
 * check this very frequently and only pay for an actual Electron
 * `clipboard.read()` call on the rare tick where it's moved.
 *
 * `generalPasteboard` is a process-wide singleton the caller doesn't own
 * (the selector isn't `alloc`/`new`/`copy`-prefixed), so it's never
 * released — same manual-reference-counting convention every other
 * Objective-C call in this codebase already assumes, just without a
 * bridging crate to enforce it for us here.
 */
export declare function pasteboardChangeCount(): number

/**
 * Shows a form anchored to the bottom-right of `parent_view`'s window, replacing
 * whatever panel is open. `on_event` is called with `{ kind: "submit", value }`
 * each time the user saves (the form then waits — see `fail_actions_form` and
 * `close_actions_form`), and with `{ kind: "cancel" }` when it's dismissed by
 * the user (`"back"`: Esc, Cancel) or lost (`"dismissed"`: focus moved away, or
 * another panel replaced it).
 */
export declare function showActionsForm(parentView: Buffer, spec: ActionsFormSpec, onEvent: (event: FormEvent) => void): void

/**
 * Shows the panel anchored to the bottom-right of `parent_view`'s window.
 *
 * `parent_view` is Electron's `BrowserWindow.getNativeWindowHandle()` (an
 * `NSView*`). `on_event` is called once: with `{ kind: "select", id }` when a
 * row is chosen, or `{ kind: "close" }` when dismissed (Esc, focus loss,
 * `closeActionsPanel`). Any panel already open is dismissed first.
 */
export declare function showActionsPanel(parentView: Buffer, title: string, items: ActionsPanelItem[], onEvent: (event: PanelEvent) => void): void

/**
 * Starts the global-hotkey watcher: a background thread installs a
 * session-level `CGEventTap` (requires the user to have granted Magibar
 * Input Monitoring access — see the module doc comment) and runs a
 * `CFRunLoop` to keep receiving callbacks on it, invoking `callback` with
 * the registered id whenever a bound accelerator fires. Entries are
 * registered/unregistered afterward via the returned `HotkeyWatcher`.
 *
 * Blocks briefly waiting for the background thread to finish setting up, so
 * a failure (permission not granted, or run-loop-source creation failing)
 * can be reported by returning a watcher whose `tap` is already 0 rather
 * than one that silently never calls back — same contract as
 * `native/win`'s `start_hotkey_watcher`.
 */
export declare function startHotkeyWatcher(callback: ((err: Error | null, arg: string) => any)): HotkeyWatcher

/**
 * Toggles native macOS fullscreen on the focused window — the same effect as
 * clicking-and-holding the green traffic-light button and choosing "Enter/Exit
 * Full Screen." Not every window supports this; returns whether the write
 * succeeded.
 */
export declare function toggleFullscreen(pid: number): boolean
