[package]
name = "linux_native"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", features = ["napi9"] }
napi-derive = "3"
sysinfo = "0.32"
listeners = "0.6.1"
x11rb = { version = "0.14.0", features = ["xfixes"] }
serde = "1"
zbus = "5"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
