/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Handle for the background clipboard watcher `start_clipboard_watcher` starts. Dropping this
 * without calling `stop()` leaks the watcher's X11 connection and thread for the rest of the
 * process's life — callers must `stop()` it explicitly (e.g. on app quit), matching
 * `ClipboardPoller.stop()` on the TS side and `@magibar/win`'s `ClipboardWatcher`.
 */
export declare class ClipboardWatcher {
  /**
   * Wakes the watcher thread (via a self-addressed `ClientMessage`, since
   * `wait_for_event()` is otherwise blocked on the socket) and joins it.
   * Idempotent — a second call is a no-op.
   */
  stop(): void
}

/**
 * Handle for the background hotkey watcher `start_hotkey_watcher` starts —
 * mirrors `native/win`/`native/mac`'s `HotkeyWatcher` shape so `main/
 * native/hotkeys.ts` needs no Linux-specific branch of its own. Owns one
 * background worker thread that serializes `register`/`unregister` into
 * `gsettings`/`dconf` CRUD calls and, on the same connection, hosts the
 * `Trigger` D-Bus service for the life of the process.
 */
export declare class HotkeyWatcher {
  /**
   * Parses `accelerator` and, if it parses, round-trips a CRUD request to
   * the worker thread and returns whether every `gsettings`/`dconf` call
   * actually succeeded — see `upsert_custom_keybinding`'s doc for why this
   * is a real synchronous answer. `false` for an unrepresentable
   * accelerator string without even reaching the worker.
   */
  register(id: string, accelerator: string): boolean
  /** Idempotent — removing an id that isn't registered is a no-op. */
  unregister(id: string): void
  /**
   * No-op — a `media-keys` custom keybinding has no way to observe an
   * arbitrary keystroke (it only ever runs its command once bound); a
   * shortcut recorder here relies on the renderer's own DOM listener
   * instead, same as every other engine that can't do this.
   */
  startCapture(callback: ((err: Error | null, arg: string) => any)): void
  /** No-op counterpart to `start_capture`. */
  stopCapture(): void
  /**
   * Stops the worker thread (which also drops the `Trigger` D-Bus service's
   * connection, releasing `HOTKEY_BUS_NAME`). Deliberately leaves every
   * registered custom keybinding in place rather than tearing them down on
   * every app quit — they're inert (their `Trigger` call just fails to find
   * anything listening) until the app starts again, and re-creating them
   * from scratch on every launch would mean a brief window after each
   * startup where the user's configured hotkey doesn't work yet. Idempotent.
   */
  stop(): void
}

/**
 * The active window's id, or `0` if none (or the only candidate was `exclude`
 * — the launcher's own X11 window id, so a stray capture of the launcher
 * itself is discarded rather than moved later).
 */
export declare function activeWindow(exclude: number): number

/**
 * Moves and resizes the window to `rect`. Unmaximizes first — most window
 * managers ignore a `ConfigureWindow` resize/move on an already-maximized
 * window, the same reason the mac/Windows paths restore the window before
 * repositioning it. That step is best-effort (a window that was never
 * maximized has nothing to remove, and this shouldn't block the actual move);
 * the `ConfigureWindow` call is what determines the return value.
 */
export declare function applyWindowRect(id: number, rect: LinuxRect): boolean

/**
 * The window's current position (translated to root/screen coordinates) and
 * size, or `null` if unavailable (invalid id, or the X11 connection is down).
 */
export declare function getWindowRect(id: number): LinuxRect | null

/**
 * Whether any X11/XWayland window exists at all right now — checked via
 * `_NET_CLIENT_LIST` on the root window, and `false` if the X11 connection
 * itself can't be established (e.g. a pure-Wayland session with no XWayland).
 * A window-management feature offered on a desktop with zero reachable
 * windows would just silently no-op every command, so this is used to hide
 * the feature entirely instead.
 */
export declare function hasXwaylandWindows(): boolean

/**
 * Terminates `pid` — `SIGTERM` (a graceful "Quit") when `force` is `false`,
 * `SIGKILL` ("Force Quit") when `true`. Returns `false` if the process no
 * longer exists or the OS denies permission (not owned by this user); the
 * caller can't tell those apart from the bool alone and doesn't need to —
 * both are surfaced as the same inline error.
 */
export declare function killProcess(pid: number, force: boolean): boolean

export interface LinuxRect {
  x: number
  y: number
  width: number
  height: number
}

/**
 * Every TCP port something is listening on, with the owning pid. Empty if the
 * OS refuses to enumerate (e.g. missing permission).
 */
export declare function listListeningPorts(): Array<NativePort>

/**
 * A snapshot of every currently running process's pid, name, CPU% and
 * resident memory. Cheap to call on a poll interval (a couple of times a
 * second) — just a `/proc` walk under the hood.
 */
export declare function listProcesses(): Array<NativeProcess>

/**
 * One listening TCP socket and the process that owns it. Cheap enough (a few
 * ms) to fetch alongside `list_processes()` on every poll tick.
 */
export interface NativePort {
  pid: number
  port: number
}

/**
 * One process's identity and live resource usage, as reported by the last
 * `list_processes()` refresh.
 */
export interface NativeProcess {
  pid: number
  name: string
  /**
   * Percentage of a single CPU core (0–100 per core, so a busy multi-core
   * process can exceed 100), matching `top`'s own convention.
   */
  cpuUsage: number
  memoryBytes: number
  /**
   * Full path to the executable, when readable — lets the TS side resolve
   * an icon for it via Electron's `app.getFileIcon`. `None` for a process
   * whose executable path isn't readable (permission-restricted, or exited
   * between the refresh and this read).
   */
  path?: string
}

/**
 * Starts watching the system clipboard for changes via a true OS push notification instead of
 * polling: a background thread opens its own X11 connection, registers for `XFixes`
 * `SelectionNotify` events on the `CLIPBOARD` selection (`XFixesSelectSelectionInput` — the same
 * mechanism the `clipnotify` CLI tool is built on), and invokes `callback` with no arguments
 * once for every clipboard-ownership change. This is what lets the TS `ClipboardPoller` (see
 * `main/pasteboard-change-linux.ts`) skip its `setInterval` fallback entirely on Linux, the same
 * way `@magibar/win`'s `startClipboardWatcher` does on Windows.
 *
 * `XFixesSelectionNotify` only fires on a selection *ownership* change (a new copy), not on
 * every write within the same ownership — exactly the granularity `ClipboardPoller` wants.
 *
 * Blocks briefly waiting for the background thread to finish connecting and subscribing before
 * returning, so a failure (no X server/XWayland reachable, or the XFixes extension missing) can
 * be reported by returning a watcher whose internal window is already `0` rather than a handle
 * that silently never calls back.
 */
export declare function startClipboardWatcher(callback: ((err: Error | null) => any)): ClipboardWatcher

/**
 * Starts the global-hotkey watcher: a background thread opens a D-Bus
 * session connection, claims `HOTKEY_BUS_NAME`, and hosts `HotkeyService`
 * on it (serviced automatically by `zbus`'s own internal executor for as
 * long as the connection stays open — no explicit dispatch loop needed),
 * then processes `register`/`unregister` calls (relayed from the returned
 * `HotkeyWatcher`) into `gsettings`/`dconf` CRUD against that same
 * connection's lifetime.
 */
export declare function startHotkeyWatcher(callback: ((err: Error | null, arg: string) => any)): HotkeyWatcher

/**
 * Toggles EWMH `_NET_WM_STATE_FULLSCREEN` on the window — broadly supported
 * across X11 window managers (the same mechanism `wmctrl -b toggle,fullscreen`
 * drives).
 */
export declare function toggleFullscreen(id: number): boolean
